### ISSUE TITLE
[Subscribe] Checklist

### ISSUE THREAD

**Issue by youzi** [vigour-io/vjs#137]
- [x] Extend all current tests with:
  - [x] Extra updates + counters
  - [x] Removing & re-adding listeners
  - [x] Checks for binds

- [x] Strategy for removing properties and resubscribing

- [ ] Start on un subscribe
