### ISSUE TITLE
defer on emitters

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vjs#20]
## tasks
- [x] spec it!
## 
- [x] store **binds** by stamp id #94 
- [x] ~~move execPostponed / Meta to event and use event.$execute() in base emits~~
  - [x] should also add its own change emitter to postponed if defer (re add it to binds) #97 
- [x] defer is on the emitter
- [x] create an event when deferring #97  
- [x] defer is an extension on $exec emitters can always only have one defer?
  - [x]  **problem** what to do with multiple instances, make multiple defers on different bases
  - [x] share defers or do not share defers done in a special way
  - [x] check for ancestor -- i am instance x -- change on x (or postponed) ancestor is x --- update all                 instances, instances can have their unique defer thats in progress 
    do a check like: if(instance :deferOriginator ) dont update from this defer - needs #98 
- [x] add Instance orignator as information in emitters (this is not the event orignator) #98 
- [x] if defering and a new exec happen (for a different event) by default clear the old defer
## example usecases

.$emit with a defer

e.g. .$emit with a delay of 50
e.g. .$emit with a postpone of 50
e.g. .$emit with a throttle of 50
e.g. ,$emit on http.get complete
e.g. .$emit on .then (Promise )
e.g. .$emit conditional when value equals x
