### ISSUE TITLE
subscription

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vjs#23]
role of subscription is to listen on fields that are not yet there
_hard parts_
- instances
- lookUp (parent) _especially with instances_
- references and reference travelers
## tasks
- [x] spec and design it
- [x] parent (lookup) functionality
- [x] efficient way to do deeper checks
- [x] bind listeners 
- [x] remove listeners
- [x] instances
## 
- [x] resolve $base listeners that point to a parent or instance for inheritance (especially interesting for subscriptions etc)
## 

needs: #25, #3
