### ISSUE TITLE
$on , multiple listeners, remove, bound type and listens array

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vjs#25]
- [x] fix `x --ref-->  a --> b --> c` b has special listener fire within context of b and c, now only fires b
## 
- [x]  decide if keys are the best way to use on in a set
- [x] implement keys and id generator
- [x] restructure add
- [x] use setKeyInternal within lists (to create new stuff if necessary)
- [x] fix multiple listeners and inheritance
- [x] adding listeners only overwrites , make an array type/ keys for Base
- [x] now the creation stamp of listeners never gets removed should get removed as soon as the event is done executing
- [x] ~~property listener fire on _$val set and removal of val~~ do not do this use $value for this
- [x] don't necessarily need $postponed stamp on emitters (can be true when added)
- [x] removing listeners when originators get removed
- [x] remove listener (use listens array, passon and normal ref) needs: #3 
- [x] handle remove in property and change emitters
- [x] on needs to be notified if a parent instance gets removed
- [x] rename $onBase and $onPasson to passon and base
- [x] splitting `types` complicates sets with keys (e.g. key 'a' was a function now a base does not get resolved)
- [x] ~~removeListener in Storage objects in emitter~~ replaced with removeProperty (standard)
## 
- [x] ~~resolve $base listeners that point to a parent or instance for inheritance (especially interesting for subscriptions etc)~~ _moved to subscription_
## 
- [x] clean up use #32 
- [x] firing when you make an instance - one listener changes one does not
  - [x] replace the stamp gaurd on construction with on listener guards ( add stamp when listeners gets added?)
  - [x] handle multi object sets on new correctly
- [x] when making a new instance, there need to be a difference in the instance else listeners do not fire
- [x] need to track instances for on
- [x] fix updates for inherited change listeners e.g. update on an instance should update the instance
- [x] need information about instances within on
- [x] create a new instance of the storage e.g. onFn etc if necessary
- [x] add better management for instances
- [x] ~~emitters need to get by default do not update instances~~
- [x] ~~$change is not going to be the default emitter~~
- [x] ~~default is do not execute postponed~~
- [x] ~~remove files for references (nothing special)~~
- [x] handle instances for $onFn etc better
- [x] check why it does not work with the `newParent` trick in every situation
## 
- [x] binding values /w functions 
  - [x] create new `type` for bound functions (its array)
  - [x] handle arguments efficiently
  - [x] handle bind in the most efficient way
  - [x] if bound is a Base add to listens array (for remove)
  - [x] maybe add 2 listens arrays? one for onBase (basic) one for onArray
## 
- [x] listens array
- [x] do extra tests for  `new instances`
- [x] $on method `on$` needs: #17 
- [x] check if functions have to be unique (don't think so -- resolved functions are not unique) 
## 

keys for fields in $on

``` javascript

var bla = new Base({
  $on: {
    a: function() {},
    b: function() {}
  }
})
//$val overwrites _$val just as usual

```
## 

listens (bound values)

``` javascript
bla.$$on( baseX )
//this creates a new field (generates an id)
```
## 

array notation
*can also use an object (clearer, but heavier)

``` javascript
  bla.$$on([ function(){}, baseX ])
//syntax for bound listeners (array is a cheap way to store)
```
## 

array notation (multiple arguments)

``` javascript
bla.$$on([ function(){}, baseX, myArg ])
//first args is the bind , rest is apply for the listener (after event and meta)

bla.$$on([ function(){}, false, argX ])
//if first arguments is false uses default behaviour
```
