### ISSUE TITLE
$remove

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vjs#3]
## questions
- [x] will we use a set with `null`as a remove ? (makes things easier , especially when passing events)
- [x] ~~how to deal with instances (since you don't know if you have instances, only when listening)?, relevant for parents e.g. `a --> b`  `a.xx.remove()` now notify b as well~~ resolved and implemented
## tasks
- [x] null implementation handle blocks
- [x] $remove method
- [x] ~~$onRemove $on~~ _replaced with meta = true or property emitter_
- [x] $handeling remove as a set (e.g. make new instance if necessary)
- [x] $listens array to remove everywhere where listening
  - [x] $listenOnBase
  - [x] $listenOnPasson
- [x] fire $change listener
- [x] fire $property listener
- [ ] fire $reference listener
- [x] handle set objects with null
- [x] handle removal of instances, `a --> b`  `b.xx.remove() b.xx === a.xx` now detach b from a.xx
- [x] first argument to remove set on true, remove all instances ( not only context ) move event to second arg spot
- [x] redo this with a getter that resets context
- [x] add extra hook in remove for `remove this from context but not myself` ( important for $on )
