### ISSUE TITLE
$emit instances tests

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vjs#40]
## $change 
- [x] resolve (fix `x --ref-->  a --> b --> c` b has special listener fire within context of b and c, now only fires b) first
- [x] test passons
- [x] instance of c
- [x] extra listener on a
- [x] changing val listener on c
- [x] new instance extra field (extra field should not fire original should fire)

$change-references test-file
- [x] remove
- [x] changing values from listener to non - listeners ( has to remove stuff )
- [x] making instances of referenced observables
  - [x] figure out how to handle

$removal and overwrites
- [x] buttload of tests for overwrites and removals
- [x] remove listeners (see if instances get resolved needs #3 )
## combined
- [x] finish all individual tests first, finish #39 
- [x] instances
- [x] $new
- [x] add a test for adding more instances in a function listener
- [x] order of execution
- [x] custom emitter
- [x] [BUG] new parents see #62 
## perf
- [x] start of perf tests
- [x] ~~perf tests for instances -- if you do something like .remove dont do instances checks for instances (since it will hapen anyways)~~ moved to separate issue
