### ISSUE TITLE
resolve nested sets

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vjs#71]
``` javascript
var a = new obs({ 
 b: {
   $on: {
     $change:function() {
        this.$set({
          c:true
        })
      }
    }
  }
})
var b = new a()

b.b.$val = {
  etc:true
}
```

``` javascript
var a = new obs({ 
 b: {
   $on: {
     $change:function() {
         console.log('!')
      }
    }
  }
})
var b = new a()

a.b.$val = 'marcus'
```

this this not fire! 
especially sucks when doing instances
## tasks
- [x] enhance remove test
- [x] add test in combined
## needs
- [x] binds in emitter #99
- [x] laststamp resolve issue 
- [x] fix bugs in references
- [x] clean up pushBind
- [x] remove needs to fire correct contexts
- [x] remove stopped working
- [x] nested parent instance working #107
