### ISSUE TITLE
emitter - emit needs possiblity to add context to a bind

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vjs#99]
## tasks
- [x] check for if context when binding
- [x] ~~~make a special storage type using arrays~~~ make 2 __binds
- [x] run trough both normal binds and context resolved
  ~~~`if binds[stamp].$context` - do $context and $val,~~  `if emitter.$contextBound && $bound`
- [x] when starting the context loop remember the current context and resolve at the end
- [x] remember context when starting to loop trough context binds
- [x] ~~first loop trough $val then $context~~ other way around
- [x]  clean up bind (reuse many functions for the pushBind method)
- [x] clean up instances
- [x] clean up exec
- [x] remove checks in exec -- wrong
- [x] use resolver (in a cleaner way)
- [x] double check issue with remove
- [x] add event to resolvecontext again
## 
- [x] double check if the way last stamp is set (when it arrives at non-context emitters) is enough
  - [x] probably should be able to share it over each context emitter thing (weird that it gets executed and not on postponed)
## 
- [x] use a cleaner implementation of #104
  to prevent stuff like:

``` javascript
        bind._$context = contextBinds[i][1]
        bind._$contextLevel = contextBinds[i][2]
        bind._$contextKey = contextBinds[i][3]
```
## performance
- [x] test perf
- [x] use  and enhance perf tests for on
- [x] check if arrays may be faster
- [x] check if storing in another object then **bind** at top level may be faster
